#!/usr/bin/env bash
echo "Collecting Output..."
node Test1.js > output1.txt

echo "======================================================="
echo "Test 1"
echo 
python Test1.py < output1.txt

echo "======================================================="
echo "Test 2"
echo 
python Test2.py < output1.txt

echo "======================================================="
echo "Test 3"
echo 
python Test3.py < output1.txt

echo "======================================================="
#Clean up
rm -f output1.txt